### ISSUE TITLE
Create a new release for Plone 4.3.x

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.widgets#100]
@thet How does it look for creating a release (probably 1.8.0) for Plone 4.3.x with the last known working set of mockup? Anything I could do to help you on that?

**Comment by datakurre** [comment]
@frapell Last time I asked @thet about a release, he was waiting for some fixes you wanted to be there. Any news about those?

**Comment by datakurre** [comment]
plonejsi18n should have a working default for Plone 4.3 (or completely disabled); now it defaults to host root, causing 404s for each request

**Comment by frapell** [comment]
@datakurre unfortunately not, I haven't had time to properly talk with @thet on what is going to be the idea... for what I understand, it would be using branch 1.x from mockup, but I see it doesn't have a commit since January, so not sure.

BTW, the plonejsi18n problem you mention is related to plone/mockup#482 where the body is not yet available when this code from https://github.com/plone/mockup/blob/f52fdb1905549cfd5b0245bc54760a2ad84a4237/mockup/js/i18n.js is executed

```javascript
    self.baseUrl = $('body').attr('data-i18ncatalogurl');
    if (!self.baseUrl) {
      self.baseUrl = '/plonejsi18n';
    }
```

**Comment by datakurre** [comment]
@frapell Thanks for your thoughts.

My context here is that we are going to make an alpha release of Plone Mosaic soon and outdated p.a.widgets is the only thing preventing it from working on Plone 4. :(

p.a.widgets 1.7.1 comes with a bundle without pat-registry and I also get an error, which I cannot debug, because of missing non-minified bundle in p.a.widgets 1.7.1 release.

I tried to work out without p.a.widgets for Plone 4, but it's impossible because Plone Mosaic required TinyMCE 4.

If I just build the widgets bundle from mockup master, I get the plonejsi18n errors, warnings about patterns missing name or triggger (because of mockup-registry => pat-registry change) and weird errors from select2 like

    "patterns.pat.select2:" "Failed while initializing "select2" pattern." ++resource++plone.app.widgets.js:8:8063
    "patterns.pat.select2:" "query function not defined for Select2 s2id_autogen9" ++resource++plone.app.widgets.js:8:8063

**Comment by vangheem** [comment]
I thought we weren't doing mosiac for 4.3? @bloodbare

**Comment by datakurre** [comment]
@vangheem @bloodbare We are not, but we cannot prevent me from keeping it Plone 4.3.x compatible (unless p.a.widgets release does it). :+)

**Comment by frapell** [comment]
@datakurre FWIW, I pulled in version 2.0.2 and compiled and worked just fine for a custom build I have for a client. Some "This pattern does not have a name so it will not be registered" logs to the dev console, which I didn't have time to debug yet...

**Comment by datakurre** [comment]
@frapell Any idea, why I get those select2 errors? (And maybe related to those, related items widget for p.a.contenttypes is broken.)

FWIW Mosaic would have two requirements for Plone 4.3 support:

* fixed plone.app.widgets
* default (not customized) main_template

Of course, it only works for Dexterity types (because it's a behavior), but it won't really require e.g. plone.app.contenttypes and should coexist nicely with all legacy content.

**Comment by frapell** [comment]
@datakurre sorry, no... In my case, I had to create a fork of p.a.widgets to use with clients using Plone 4, because I didn't have the time to properly contribute here due to the fast pace at which stuff changes...

You can find them in:

https://github.com/enfold/plone.app.widgets/tree/plone4
https://github.com/enfold/mockup/tree/4.3

and a released package in:

https://pypi.enfoldsystems.com/pypi/plone.app.widgets/

Sorry I cannot be of further help

**Comment by datakurre** [comment]
@frapell @thet @jcbrand FWIW. When I apply the latest mockup master on top of plone.app.widgets 1.7.1. on Plone 4.3.x, pat-relateditems get applied twice, resulting select2 related errors ("query function not defined...") and broken relateditems widget. This is probably related to mockup-registry being replaced with pat-registry, but probably somehow fixed for Plone 5, because nobody has complained. I've managed to workaround (to avoid pat-relateditems initing itself twice), but have no idea of the real issue here.

**Comment by jcbrand** [comment]
@datakurre My guess is that the pattern gets scanned twice. This might be perhaps because both registries are still active.

The mockup registry should not be used at all. You could test this by looking in the developer console to see if the registry in mockup-core is being loaded and whether it does any scanning.

**Comment by datakurre** [comment]
@jcbrand That's a plausible guess, but my widgets bundle (generated from the mockup master) does not include mockup-registry.

**Comment by jcbrand** [comment]
@datakurre Is there someplace I can test this without having to set it up myself? I should be able to relatively quickly see what's going on if I can put a breakpoint in pat-relateditems' initialize method.

**Comment by datakurre** [comment]
@jcbrand Thanks. Later this week or early next week. I'll ping. (Mosaic will now override widgets bundle on Plone 4 to fix this issue with outdated p.a.widgets release and the issue can be seen once I fix the Heroku demo deployment for Mosaic.)

**Comment by thet** [comment]
@datakurre please try out with latest plone.app.widgets from github master.
if there are no issues, it should now be ready to make a release - the issues i had with it are resolved (tinymce linking and image upload troubles) and i cannot reproduce the relateditems issue you have.

**Comment by datakurre** [comment]
@thet Thanks. I'll check it out. I've been using the master for a couple of weeks and it's been working otherwise, but still causing the related items issue. I've not yet tried the latest one.

**Comment by datakurre** [comment]
@thet The new master works also fine.

Also I found the issue causing related items issue. Mosaic layout pattern was requiring the pattern registry (previously mockup registry) for doing scanning and initialization by itself. I'm not sure why. Ramon probably knows. Looked like legacy stuff from iframe toolbar experiments. Once that was removed, everything seem to work fine.

+1 for making p.a.widgets release (1.8.0) from the current master

**Comment by datakurre** [comment]
@thet How have you handled the issue of 404s for jsi18n requests with Plone 4.3.x? Is there 4.3.x compatible version of p.a.layouts (or someting else), which adds the correct URL for those into body?

**Comment by thet** [comment]
my attempt was to allow plonejs18n on all contexts (``for="*"``), but that ideas wasn't liked too much because of caching issues (@davisagli). but actually caching isn't an issue, AFAIK, because if there is no url provided, it calls the plonejsi18n or whatever that view is called on "/".

however, i could live for Plone 4.3 with this workaround, while in Plone 5 it's working fine. What do you think, can you contribute a fix to p.a.layouts or should we go with my workaround?

**Comment by vangheem** [comment]
Why not just provide a shim jsi18n for plone 4 that doesn't do anything and in the grunt build, override the the translate path to your shim file.

The shim would just do: 

define('translate', [], function(){
  return function(val){ return val; };
});

**Comment by vangheem** [comment]
Or just change the translate mechanism to not default to a url--to require a url specified on the body tag to work. I would be okay with that.

**Comment by datakurre** [comment]
@thet How about the latter proposal from @vangheem?

**Comment by thet** [comment]
@vangheem, i'm not sure if i understood your first idea.
but i think having this plonejsi18n view called on "/" will work quite ok, not? it's also just for plone 4, and it's only in plone.app.wigets 1.x. most of the time, it's the plone root anyways, sometimes it's a childsite/INavigationRoot and via development or rare cases it's the zope root.

**Comment by datakurre** [comment]
@thet Agreed that it's not a blocker. Release? :)

**Comment by thet** [comment]
@datakurre done! https://github.com/plone/plone.app.widgets/issues/100 finally. i have the feeling that there will be some more minor plone.app.widget releases soon. will see.

@datakurre i have granted you the owner role on pypi

**Comment by datakurre** [comment]
@thet Thanks a lot! Now we can advertise the upcoming Mosaic alpha release for both Plone 4 and Plone 5 as soon as @optilude has given PyPI ownership of plone.app.drafts to Eric :-)
