### ISSUE TITLE
link/image browser search entire site is not working

### ISSUE THREAD

**Issue by 2silver** [plone/plone.app.widgets#102]
- Create Page
- Write Text
- Highlight Text
- Add Link
- search for content in other folders return no results

For example:
edit Document in /en/about-us/rights
search in "plonebrowser" for project (located in /en/documents/files/project) returns "No matches found"

If click on the house, search seems to be limited to root path, but not in "entire site"

Is already working in commit ccca02d569f1df7f847355391dd7d3b821d6b337

Working on branch 1.x

---

:edit:
Seems that the default mode in TinyMCE Editor Link-Popup is "browse", and in default "Related Items"-Widget is "search"

**Comment by jensens** [comment]
I am pretty sure this works in Plone 5.
