### ISSUE TITLE
Problems on new Plone 4.3.5 site with latest plone.app.contenttypes and plone.app.widgets

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.widgets#105]
I just installed a brand new Plone 4.3.5 site with 

      - "plone.app.contenttypes = 1.1b4"
      - "plone.app.widgets = 1.8.0"

I see the following warnings in the js console:

```
patterns.Mockup Base: This mockup pattern without a name attribute will not be registered!
patterns.Mockup Base: The mockup pattern 'plone-widgets' does not have a trigger attribute, it will not be registered.
```

When I go edit a page, most of the widgets seem to work fine, but some do not.  For example the usual grey tabs across the top (Default, Categorization, Dates, Creators, Settins) don't show up.

**Comment by jensens** [comment]
same here - any solution available?

**Comment by frisi** [comment]
i also get the warnings on plone 4.3.6 using p.a.widgets 1.8.0 and p.a.contenttypes git branch 1.1.x

the problem with form-tabs has been reported  in #104. dunno if the warnings have to do with it. i also re-activated form_tabbing.js as a workaround.

**Comment by fulv** [comment]
I don't know whether the warnings point to an actual problem, but I managed to get rid of the first set of five warnings (`patterns.Mockup Base: This mockup pattern without a name attribute will not be registered!`) by doing the following.  I wish I could point to a commit, but I can't figure out which branch/tag (of mockup, I assume) p.a.widgets 1.8.0 is built from.

The following all extend `LinkType`:  `InternalLink`, `UploadLink`, `ImageLink`, `EmailLink`, `AnchorLink`.

So, first, I added a `name` attribute to each of them.  But that's not enough, because after they have names, then it complains that they don't have triggers.  So I made the properties object that is passed to `.extend` get some default values from the parent (`LinkType`):

    var ImageLink = InternalLink.extend(_.defaults({
      name: "ImageLink",

      toUrl: function() {
        var value = this.value();
        return this.tinypattern.generateImageUrl(value, this.linkModal.$scale.val());
      }
    }, LinkType));

The two diffs here are the `name:`, and the `_.defaults(......, LinkType)`.

I have no idea whether this will break anything else, but I'd be happy to commit this change if it's ok and someone could point me to the right branch/whatever.

This does not fix the `patterns.Mockup Base: The mockup pattern 'plone-widgets' does not have a trigger attribute, it will not be registered.` warning.

**Comment by vangheem** [comment]
You can ignore those warnings. They are not errors.

**Comment by fulv** [comment]
Good to know, but polluting the console with warnings that have to be ignored is not good practice, either.

**Comment by vangheem** [comment]
probably be better if we modify https://github.com/plone/mockup-core/blob/master/js/pattern.js#L116 to not log those cases.

**Comment by vangheem** [comment]
Or to make InternalLink, UploadLink, etc not actually use base pattern class.

**Comment by vangheem** [comment]
I'd probably change those logging statements to info instead of warn: https://github.com/plone/mockup-core/blob/master/js/pattern.js#L116

then that'd fix all the console noise.
