### ISSUE TITLE
There is no profile to be registered

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.widgets#118]
Plone 5.0 ships with plone.app.widgets 2.0.1, and the main `configure.zcml` in both the master branch and in the 2.0.1 tag contain this:

```
  <genericsetup:registerProfile
    name="default"
    title="Plone Widgets"
    directory="profiles/p5"
    description="Better widgets for Plone"
    provides="Products.GenericSetup.interfaces.EXTENSION"
    for="Products.CMFPlone.interfaces.IPloneSiteRoot"
    />
```

However, there is no profile directory, so this looks like something left over from a previous version.

I've already submitted a pull request, but it's failing tests, probably because this package has been failing for quite some time.
https://github.com/plone/plone.app.widgets/pull/117

**Comment by jensens** [comment]
Meanwhile, someone commented on this, so I think we can close this one
```
<!-- BBB. Dummy profile for Plone 4 compatible Plone 5 packages, which need
       plone.app.widgets to be installed in Plone 4. -->
```
