### ISSUE TITLE
Is the master branch testable?

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.widgets#119]
In the master branch, `develop.cfg` extends from `http://dist.plone.org/release/4.3-latest/versions.cfg`.  Should the master branch not be targeting plone 5?

Also, in the 2.0.1 tag, `develop.cfg` has this under `[sources]`:

```
plone.app.widgets = git git@github.com:plone/plone.app.widgets.git branch=master full-path=${buildout:directory}
```

Note the branch.

How is this supposed to be tested?

**Comment by vangheem** [comment]
master is only supposed to be plone 5.
