### ISSUE TITLE
mockup-patterns-base.js (404 error ) on 1.x branch - Plone 4.3.7

### ISSUE THREAD

**Issue by Gomez** [plone/plone.app.widgets#139]
One on my sites work with p.a.widgets == 1.8.0. To get some fixes in, i used the branch 1.x. Unfortunately there are script errors: 

```
Error: Script error for "mockup-patterns-base"
http://requirejs.org/docs/errors.html#scripterror
 ++resource++plone.app.widgets.js:1:1312
Error: Script error for "mockup-patterns-modal"
http://requirejs.org/docs/errors.html#scripterror
```

Because the files are missing:

```
http://localhost:8080/Plone/en/mockup-patterns-base.js (404)
```

Coud be a package problem? Can some1 confirm and point me to some more infos? 

We should release 1.8.1, the 1.8.0 package is a year old.

**Comment by petschki** [comment]
is this still valid in 1.9.1 ? I think we can close this ...

**Comment by Gomez** [comment]
yes closing
