### ISSUE TITLE
tiny uses transformed text on archetypes richtextfields

### ISSUE THREAD

**Issue by frisi** [plone/plone.app.widgets#145]
using tinymce4 from plone.app.widgets on archetypes textfields created without the package before will result in a not working image-dialog for existing images because tiny needs to parse uid and image scale out of a url like this:

``` html
<img alt="Image Title" class="image-left" src="image-test.jpg/@@images/f8f4827e-5407-4d3a-a171-445c3609f136.jpeg" title="Image Title" />
```

(see https://community.plone.org/t/images-inserted-with-plone4-broken-on-plone5/2722/5?u=frisi for a full explanation)

this of course, also breaks functions such as captioned images (where the output transforms `<img class="captioned".../>` into 

``` html
<dl style="width:620px;" class="image-inline captioned">
<dt><a rel="lightbox" href="/path/to/image.jpg"><img src="image.jpg/@@images/c89b9bf7-b3b9-4eed-828c-6e6bc0ffbbbe.jpeg" alt="title" title="title" height="413" width="620" /></a></dt>
 <dd class="image-caption" style="width:620px;">image description text</dd>
```

in addition, saving this text after opening it will break the image dialog forever and add lots of unwanted code to the raw textfield

**Comment by frisi** [comment]
@pcdummy will soon add a pr for this

**Comment by fredvd** [comment]
@frisi @thet this issue can be closed then, right?

**Comment by frisi** [comment]
yes i guess so. thanks for your nudge fred ;-)
