### ISSUE TITLE
1.x releases

### ISSUE THREAD

**Issue by petschki** [plone/plone.app.widgets#175]
can we release 1.9.0 and 1.10.0 ?

**Comment by jensens** [comment]
cc @plone/release-team

**Comment by mauritsvanrees** [comment]
- [1.9](https://pypi.org/project/plone.app.widgets/1.9/) was released in June last year, and [1.9.1](https://pypi.org/project/plone.app.widgets/1.9.1/) in February this year.
- [1.10](https://pypi.org/project/plone.app.widgets/1.10/) was released on 1 September.

Note that it is not 1.9.0, but 1.9, and not 1.10.0, but 1.10. The release team likes it better without the extra zero at the end, so it stands out a bit more in a version list: it makes it easier to spot that the version has new features (provided the package uses semantic versioning, which we try to do in Plone, but sometimes it is not practical).

**Comment by petschki** [comment]
thank you. I think the latest 1.x release should be linked in the latest p.a.widgets README.rst ... so anybody landing on pypi can find it easily ... @thet what do you think?
