### ISSUE TITLE
new release 1.11

### ISSUE THREAD

**Issue by petschki** [plone/plone.app.widgets#188]
@thet @ale-rt anybody of you willing to release 1.11 ... this would fix:

- https://github.com/plone/plone.app.widgets/issues/162
- hard dependency on `z3c.releationfield`
- some configuration convenience

**Comment by petschki** [comment]
PS: or 1.10.1 is also OK 😉

**Comment by ale-rt** [comment]
+1 for releasing the 1.x branch but I have no pypi power. CC @plone/release-team
