### ISSUE TITLE
How to use the results obtained from QueryStringFieldWidget in preview?

### ISSUE THREAD

**Issue by ironmaniiith** [plone/plone.app.widgets#200]
Hi,
I'm working on a plone project as part of GSOC'19. My project is on import export and for that, I had integrated QueryStringFieldWidget in my project for export functionality so that I can perform efficient queries on the content and can export content based on the result of the query returned.
What I am unable to figure out is, how to use the results that are shown in the preview section of the widget.

![Screenshot from 2019-06-23 19-25-23](https://user-images.githubusercontent.com/9266422/59977272-e4812480-95ec-11e9-9b3f-99b2c4d6a56b.png)

In the attached screenshot, I basically want to know those 3 matched items so that I can perform operation on them afterwards.

Edit: I tried to extract data by adding a button handler, but the data that I'm getting on calling `self.extractData()` does not give me the actual files/folders that matched the query, instead it gives me the json file containing the information of the query itself

Thanks in advance.

**Comment by djay** [comment]
This is a question not  bug so would have got the best result from community.plone.org
