### ISSUE TITLE
TinyMCE: "original" image scale breaks.

### ISSUE THREAD

**Issue by polyester** [plone/plone.app.widgets#71]
Using the following pins against a Plone 4.3.3:

plone.app.event=2.0a4
plone.app.contenttypes=1.2a4
plone.app.widgets=1.7
plone.app.jquery=1.9.1.1
plone.app.querystring=1.2.2
z3c.form=3.2.1
plone.app.vocabularies=2.1.16
plone.app.portlets = 2.5.1

When using TinyMCE, images work nicely. Drag 'n drop from desktop, whatever. Only setting the scale to "original" breaks. 

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.edit, line 54, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.dexterity.browser.edit, line 29, in handleApply
  Module z3c.form.group, line 126, in applyChanges
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.dexterity.content, line 664, in reindexOnModify
  Module Products.CMFCore.CMFCatalogAware, line 88, in reindexObject
  Module Products.CMFCore.CatalogTool, line 301, in reindexObject
  Module Products.CMFPlone.CatalogTool, line 353, in catalog_object
  Module Products.ZCatalog.ZCatalog, line 476, in catalog_object
  Module Products.ZCatalog.Catalog, line 353, in catalogObject
  Module Products.ZCTextIndex.ZCTextIndex, line 180, in index_object
  Module plone.indexer.wrapper, line 65, in __getattr__
  Module plone.indexer.delegate, line 18, in **call**
  Module plone.app.contenttypes.indexers, line 51, in SearchableText_document
  Module plone.app.textfield.value, line 71, in output
  Module plone.app.textfield.value, line 97, in output_relative_to
  Module plone.app.textfield.transform, line 64, in **call**
TransformError: Error during transformation

**Comment by jensens** [comment]
Meanwhile, this is a pattern, a new TinyMCE etc. I close this one.
