### ISSUE TITLE
TinyMCE: styles are missing

### ISSUE THREAD

**Issue by polyester** [plone/plone.app.widgets#72]
using following pins against Plone 4.3.3

plone.app.event=2.0a4
plone.app.contenttypes=1.2a4
plone.app.widgets=1.7
plone.app.jquery=1.9.1.1
plone.app.querystring=1.2.2
z3c.form=3.2.1
plone.app.vocabularies=2.1.16
plone.app.portlets = 2.5.1

TinyMCE shows up, but is missing all styles from portal_tinymce/@@tinymce-controlpanel

**Comment by jensens** [comment]
workaround for 1.x branch at 79ede2f5ef53797c79cd2597dd9ea0a9ab41ec3a

**Comment by petschki** [comment]
@jensens did you check the branch for this issue: https://github.com/plone/plone.app.widgets/blob/issue-72-use-controlpanelsettings/plone/app/widgets/utils.py this is all ready for 1.x branch

**Comment by jensens** [comment]
can we merge it?

**Comment by petschki** [comment]
:+1:  for me ... @frisi ?

**Comment by jensens** [comment]
@petschki so we need a Pull Request ;)

**Comment by petschki** [comment]
@jensens done #91 .. but it conflicts with your changes .. of course ..

**Comment by jensens** [comment]
sure, i'll revert them first
