### ISSUE TITLE
The 'publication date' on my content jumps by 8 hours (my timezone) each time I save a piece of content

### ISSUE THREAD

**Issue by neilferreira** [plone/plone.app.widgets#74]
Each time I save a piece of content via the content_status_modify view the publication date jumps by 8 hours.

My server is in GMT+8

Same behaviour as reported here https://dev.plone.org/ticket/10141

**Comment by jensens** [comment]
probably outdated. works here (GMT+2).  One issue is left in folder_contents (own ticket is open),
