### ISSUE TITLE
Have the select2 widget play nice with a DataGridField

### ISSUE THREAD

**Issue by frapell** [plone/plone.app.widgets#79]
Using a drop down with the select2 widget inside a DataGridField will cause incorrect positioning when adding additional rows.

Steps to reproduce:

Install collective.z3cform.datagridfield and create a content type using this as model:

``` xml
<model xmlns:security="http://namespaces.plone.org/supermodel/security" xmlns:marshal="http://namespaces.plone.org/supermodel/marshal" xmlns:form="http://namespaces.plone.org/supermodel/form" xmlns="http://namespaces.plone.org/supermodel/schema">
  <schema>
      <field name="dgf_field" type="zope.schema.List">
        <description/>
        <required>False</required>
        <title>DGF Field</title>
        <value_type type="collective.z3cform.datagridfield.DictRow">
          <schema>.interfaces.IDGFSchema</schema>
        </value_type>
        <form:widget type="collective.z3cform.datagridfield.DataGridFieldFactory"/>
      </field>
  </schema>
</model>
```

Create the interface schema:

``` python
from plone.app.widgets.dx import SelectFieldWidget
from plone.directives import form
from zope.interface import Interface
from zope.schema.vocabulary import SimpleVocabulary
from zope import schema


class IDGFSchema(Interface):

    form.widget(drop_down=SelectFieldWidget)
    drop_down = schema.Choice(
        title=u"Drop down",
        required=False,
        vocabulary=SimpleVocabulary.fromValues([u'foo',u'bar'])
    )
    number = schema.Int(
        title=u"Number",
        required=False,
        )
```

You will notice that the Select2 drop down shows fine, but as soon as you add a new row, when you try to open the new drop downs, the content is placed at 0px top, 0px left and 0px width.

However, if you manage to save with several rows and you edit the content again, all existing drop downs will show at the correct place, and only new ones will be missplaced.

Now, I'm not 100% sure if we need to fix this here, or in collective.z3cform.datagridfield package...

**Comment by jensens** [comment]
should work meanwhile
