### ISSUE TITLE
plone.app.widgets with plone.app.multilingual leads to @@qsOptions 404

### ISSUE THREAD

**Issue by andreesg** [plone/plone.app.widgets#81]
Hi,

I'm using plone.app.widgets 1.7.1 with plone.app.multilingual 1.2
While creating a Collection inside a language folder, for instance: example.com/en/ a 404 error is thrown in example.com/en/@@qsOptions.

Tried to use @@qsOptions in example.com/@@qsOptions and it returns the data without any problem.

Edit: I noticed that the qsOptions page is registered with Products.CMFPlone.interfaces.IPloneSiteRoot 

Please let me know if there's something else I can do to help
André

**Comment by jensens** [comment]
probably outdated
