### ISSUE TITLE
Running plone.app.widgets tests with other coredev tests leads to a deadlock.

### ISSUE THREAD

**Issue by tisto** [plone/plone.app.widgets#88]
Steps to reproduce:

1) Add plone.app.widgets to plone_app_testing alltests group in buildout.coredev tests.cfg
2) Run bin/allltests --all
3) Tests will be stuck at first plone.app.widgets robot test.

**Comment by gforcada** [comment]
Obsolete, thanks to the Python 3 effort :rocket:
